version: '2'
  services:
    roundcubemail:
      image: roundcube/roundcubemail:latest
      container_name: roundcubemail
  #    restart: unless-stopped
      volumes:
        - ./www:/var/www/html
        - ./db/sqlite:/var/roundcube/db
      ports:
        - 9002:80
      environment:
        - ROUNDCUBEMAIL_DB_TYPE=sqlite
        - ROUNDCUBEMAIL_SKIN=elastic
        - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.tb.thassiapiezzaroli.com
        - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.tb.thassiapiezzaroli.com
    mailserver:
      image: ghcr.io/docker-mailserver/docker-mailserver:latest
      container_name: mailserver
      # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
      hostname: mail.tb.thassiapiezzaroli.com
      ports:
        - "25:25"
        - "465:465"
        - "587:587"
        - "993:993"
      volumes:
        - ./docker-data/dms/mail-data/:/var/mail/
        - ./docker-data/dms/mail-state/:/var/mail-state/
        - ./docker-data/dms/mail-logs/:/var/log/mail/
        - ./docker-data/dms/config/:/tmp/docker-mailserver/
        - /etc/localtime:/etc/localtime:ro
      environment:
        - ENABLE_RSPAMD=1
        - ENABLE_CLAMAV=1
        - ENABLE_FAIL2BAN=1
      cap_add:
        - NET_ADMIN # For Fail2Ban to work
      restart: always
